MxOnline/urls.py
# encoding=utf8
"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
import xadmin
from django.views.generic import TemplateView
from django.views.static import serve

from organization.views import OrgView
from users.views import LoginView, RegisterView, ActiveUserView, ResetPasswordView, ForgetPwdView, ModifyPasswordView, LogOutView
from MxOnline.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^reset/(?P<reset_code>.*)/$', ResetPasswordView.as_view(), name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPasswordView.as_view(), name="modify_pwd"),
    # 课程机构首页
    url(r'^org/', include("organization.urls", namespace="org")),
    # 课程url配置
    url(r'^course/', include("courses.urls", namespace="course")),

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # 用户相关url配置
    url(r'^users/', include('users.urls', namespace="users"))

]

apps/courses/urls.py
#encoding=utf8

from django.conf.urls import url

from courses.views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentView, CourseAddCommentView, \
    VideoPlayView

urlpatterns = [
    #课程列表
    url(r'^list/$', CourseListView.as_view(), name="course_list"),
    url(r'^detail/(?P<course_id>\d+)$', CourseDetailView.as_view(), name="course_detail"),
    url(r'^info/(?P<course_id>\d+)$', CourseInfoView.as_view(), name="course_info"),
    url(r'^comment/(?P<course_id>\d)$', CourseCommentView.as_view(), name="course_comment"),
    url(r'^add_comment', CourseAddCommentView.as_view(), name="course_add_comment"),
    url(r'^video/(?P<video_id>\d)$',VideoPlayView.as_view() , name="video_play"),
]

apps/organization/urls.py
#encoding=utf8

from django.conf.urls import url
from .views import OrgView, AddUserAskView, OrgHomePageView, OrgCourseView, OrgDescView, OrgTeachersView, \
    OrgTeacherListView, OrgTeacherDetailView, AddFavView

urlpatterns = [
    #课程机构列表页
    url(r'^list/$', OrgView.as_view(), name="org_list"),

    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    url(r'^home/(?P<org_id>\d+)$', OrgHomePageView.as_view(), name="home_page"),
    url(r'^course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name="course_page"),
    url(r'^desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name="desc_page"),
    url(r'^org_teacher/(?P<org_id>\d+)$', OrgTeachersView.as_view(), name="teachers_page"),

    #教师展示列表
    url(r'^teacher/list/$', OrgTeacherListView.as_view(), name="teachers_list"),
    #教师详情页面
    url(r'^teacher/detail/(?P<teacher_id>\d+)$', OrgTeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
#encoding=utf8

from django.conf.urls import url

from users.views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, \
    UserFavCourseView, UserFavTeacherView, UserFavOrgView, UserMessageView
from users.views import UserCourseView

urlpatterns = [
    #用户信息
    url(r'^info/', UserInfoView.as_view(), name="info"),
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),
    # 发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="send_email_code"),
    #更新用户邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),
    #用户课程
    url(r'^courses/$', UserCourseView.as_view(), name="user_course"),
    #用户收藏课程
    url(r'^fav/courses/$', UserFavCourseView.as_view(), name="user_fav_course"),
    #用户收藏教师
    url(r'^fav/teachers/$', UserFavTeacherView.as_view(), name="user_fav_teacher"),
    #用户收藏机构
    url(r'^fav/org/$', UserFavOrgView.as_view(), name="user_fave_org"),
    #用户消息
    url(r'^message/$', UserMessageView.as_view(), name="user_message"),

]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/teachers-list.html
{% extends 'base.html' %}
{% block title %}课程讲师{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>&gt;</li>
                <li>课程讲师</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class="left">
                <div class="butler_list layout">
                    <div class="head">
                        <ul class="fl tab_header">
                            <li class="{% ifequal sort '' %}active{% endifequal %}"><a href="?sort=">全部</a></li>
                            <li class="{% ifequal sort 'hot' %}active{% endifequal %}"><a href="?sort=hot">人气 ↓</a></li>
                        </ul>
                        <div class="fr butler-num">共<span class="key">{{ teacher_nums }}</span>人&nbsp;&nbsp;&nbsp;</div>
                    </div>

                    {% for teacher in teachers.object_list %}
                        <dl class="des">
                            <dt>
                                <a href="{% url 'org:teacher_detail' teacher.id %}">
                                    <div class="picpic">
                                        <img width="100" height="100" class="scrollLoading"
                                             src="{{ MEDIA_URL }}{{ teacher.image }}">
                                    </div>
                                </a>
                                <div class="btn">
                                    <div class="fr btn2 bdsharebuttonbox" data-text="授课教师-奥巴马-慕学在线"
                                         data-desc="我在#慕课网#发现了教师“奥巴马”，对学习中的小伙伴很有帮助，一起来看看吧。"
                                         data-comment="奥巴马金牌讲师，从业年限：5年">
                                        <span class="fl">分享</span>
                                        <a href="#" class="bds_more" data-cmd="more"></a>
                                    </div>
                                </div>
                            </dt>
                            <dd>
                                <a href="{% url 'org:teachers_page' teacher.id %}">
                                    <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                                </a>
                                <ul class="cont">
                                    <li>工作年限：<span>{{ teacher.work_years }}</span></li>
                                    <li>工作职位：<span>{{ teacher.work_position }}</span></li>
                                    <li>就职公司：<span>{{ teacher.work_company }}&nbsp;</span></li>
                                    <li>年龄：<span>{{ teacher.age }}</span></li>
                                    <li>教学特点：<span>{{ teacher.points }}</span></li>
                                </ul>
                            </dd>
                            <a class="buy buyservice" href="{% url 'org:teachers_page' teacher.id %}"><br>查看<br>详情</a>
                        </dl>
                    {% endfor %}


                </div>
                <div class="pageturn">
                    <ul class="pagelist">

                        {% if teachers.has_previous %}
                            <li class="long"><a href="?{{ teachers.previous_page_num.querystring }}&sort={% ifequal sort 'hot' %}hot{% endifequal %}">上一页</a></li>
                        {% endif %}
                        {% for page in teachers.pages %}
                            {% if page %}
                                {% ifequal page teachers.number %}
                                    <li class="active"><a href="?{{ page.querystring }}&sort={% ifequal sort 'hot' %}hot{% endifequal %}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}&sort={% ifequal sort 'hot' %}hot{% endifequal %}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if teachers.has_next %}
                            <li class="long"><a href="?{{ teachers.next_page_number.querystring }}&sort={% ifequal sort 'hot' %}hot{% endifequal %}">下一页</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
            <div class="right layout">
                <div class="head">讲师排行榜</div>

                {% for teacher in hot_teachers %}
                <dl class="des">
                    <span class="num fl">1</span>
                    <a href="/">
                        <dt>
                            <img width="50" height="50" class="scrollLoading"
                                 src="{{ MEDIA_URL }}{{ teacher.image }}">
                        </dt>
                    </a>
                    <dd>
                        <a href="/">
                            <h1 title="{{ teacher.name }}">{{ teacher.name }}</h1>
                        </a>
                        <p>工作年限：<span>{{ teacher.work_years}}</span></p>
                    </dd>
                </dl>

                {% endfor %}


            </div>
        </div>
    </section>
{% endblock %}

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}用户收藏{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>&gt;</li>
                <li><a href="{% url 'users:info' %}">个人中心</a>&gt;</li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right">
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:user_fave_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">

                        {% for course in fav_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}">
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav_course').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });

        $('.jsDeleteFav_teacher').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });


        $('.jsDeleteFav_org').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}用户收藏{% endblock %}
{% block right_content %}
    <div class="right">
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:user_fave_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">

                    {% for org in fav_orgs  %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:home_page' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}">
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:home_page' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}">


                                    <img src="{% static 'images/gold.png' %}">

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav_course').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ srf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });

        $('.jsDeleteFav_teacher').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });


        $('.jsDeleteFav_org').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>&gt;</li>
                <li><a href="{% url 'users:info' %}">个人中心</a>&gt;</li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的消息</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="/user/message/">个人消息</a></li>
                </ul>


            </div>
            <div class="messagelist">

                {% for message in messages.object_list %}
                <div class="messages">
                    <div class="fr">
                        <div class="top"><span class="fl time">{{ message.add_time }}</span><span
                                class="fr btn foldbtn"></span></div>
                        <p>
                            {{ message.message }}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="pageturn">
                {% if messages.has_previous %}
                    <li class="long"><a href="?{{ messages.previous_page_num.querystring }}">上一页</a></li>
                {% endif %}
                {% for page in messages.pages %}
                    {% if page %}
                        {% ifequal page messages.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if messages.has_next %}
                    <li class="long"><a href="?{{ messages.next_page_number.querystring }}">下一页</a></li>
                {% endif %}

            </div>
        </div>

    </div>
{% endblock %}